#!/usr/bin/env bash
# Distil a k6 summary into a baseline file for compare.sh.
#
#   tests/k6/baseline.sh <summary.json> <suite> > tests/k6/baselines/<suite>.json
#
# Only a handful of numbers per suite are worth gating: the ones a user feels
# (narinfo latency during eval, NAR streaming, push round trip) and the ones
# that say the server stayed healthy (failures, drops, heap). Gating every
# metric k6 emits would fail on noise nobody can act on.
#
# Tolerances are per metric because the numbers differ in how steady they are:
# a p(95) on a shared runner swings much more than a failure count.
#
# Baselines are seeded from the SINGLE-tenant run, the series perf.yml calls
# "the classic numbers, tracked release over release", and both matrix legs
# compare against it: spreading the same load over four accounts moves the
# numbers by well under the band, so one baseline per suite beats two that
# drift apart. Goroutine and heap ceilings are deliberately not here; they are
# load-shape numbers, not latency a user feels, and they live as absolute
# bounds in pressure.js.
set -euo pipefail

SUMMARY=${1:?usage: baseline.sh <summary.json> <suite>}
SUITE=${2:?usage: baseline.sh <summary.json> <suite>}

# metric<TAB>stat<TAB>tolerance, per suite. A metric absent from the summary is
# dropped with a warning rather than baselined as null.
case "$SUITE" in
perf)
  want=$(
    cat <<'EOF'
http_req_duration{scenario:narinfo_hit}	p(95)	1.0
http_req_duration{scenario:narinfo_miss}	p(95)	1.0
http_req_duration{scenario:pull_identity}	p(95)	1.0
http_req_duration{scenario:pull_zstd}	p(95)	1.0
http_req_duration{scenario:pull_big}	p(95)	1.0
http_req_duration{scenario:mixed_narinfo}	p(95)	1.0
iteration_duration{scenario:push_dedup}	p(95)	1.0
iteration_duration{scenario:push_fresh}	p(95)	1.0
http_reqs	count	0.35
EOF
  )
  ;;
pressure)
  want=$(
    cat <<'EOF'
http_req_duration{scenario:storm}	p(95)	1.0
http_req_duration{scenario:flood}	p(95)	1.0
http_reqs	count	0.35
EOF
  )
  ;;
churn)
  want=$(
    cat <<'EOF'
http_req_duration	p(95)	1.0
iteration_duration	p(95)	1.0
http_reqs	count	0.35
EOF
  )
  ;;
*)
  echo "baseline: unknown suite $SUITE (perf|pressure|churn)" >&2
  exit 1
  ;;
esac

entries=()
while IFS=$'\t' read -r metric stat tol; do
  val=$(jq -r --arg m "$metric" --arg s "$stat" \
    '.metrics[$m] | (.[$s] // .value) | select(. != null) | tostring' "$SUMMARY")
  if [ -z "$val" ]; then
    echo "baseline: $SUITE has no $metric $stat, skipping" >&2
    continue
  fi
  entries+=("$(jq -cn --arg m "$metric" --arg s "$stat" \
    --argjson v "$val" --argjson t "$tol" \
    '{key: $m, value: {($s): $v, tolerance: $t}}')")
done <<<"$want"

if [ "${#entries[@]}" = 0 ]; then
  echo "baseline: nothing extracted from $SUMMARY" >&2
  exit 1
fi

# Merge per-metric objects so two stats on one metric land in one entry.
printf '%s\n' "${entries[@]}" | jq -s --arg suite "$SUITE" '
  {
    _comment: "Generated by tests/k6/baseline.sh. Regenerate with `just re-baseline` and say in the commit message why the numbers moved.",
    suite: $suite,
    metrics: (reduce .[] as $e ({}; .[$e.key] = ((.[$e.key] // {}) + $e.value)))
  }'
